### ISSUE TITLE
.carat <li> styles do not work on Android

### ISSUE THREAD

**Issue by rdmurphy** [texastribune/newsapps-styles#15]
Checked out the style guide on my Motorola G and noticed that `.carat` isn't showing up. That's probably a sizable blocker for that feature in its current state. :\ Would be nice to test it on some other Android devices to try and pin down why.

![screenshot_2015-05-22-11-03-50](https://cloud.githubusercontent.com/assets/419145/7774901/4209c0d4-0074-11e5-9209-cca0666542ef.png)

**Comment by brickaa** [comment]
Switched out the unicode character, so it's supported by Roboto & Helvetica

HELVETICA
![screen shot 2015-05-22 at 2 12 47 pm](https://cloud.githubusercontent.com/assets/2228508/7777943/a9f16022-008c-11e5-9d6b-28884a3f8b6e.png)

ROBOTO
![screen shot 2015-05-22 at 2 12 05 pm](https://cloud.githubusercontent.com/assets/2228508/7777947/b1c8ecac-008c-11e5-86a8-f8dd74d1dd9a.png)
